problem = "matrix-completion" 
gt_path = "datasets/data-real/Alamo_gt.pt" 
shape = [1731, 1731] 
obs_path = "datasets/data-real/Alamo_obs.pt" 
dataset = "Alamo" 
unobs_path = "datasets/data-real/Alamo_unobs.pt" 
gt_mat = "datasets/datasets_matrices/Alamo.mat"
