problem = "matrix-completion" 
gt_path = "data/data-real/Notre_Dame_gt.pt" 
shape = [1659, 1659] 
obs_path = "data/data-real/Notre_Dame_obs.pt" 
dataset = "Notre_Dame" 
unobs_path = "data/data-real/Notre_Dame_unobs.pt" 
gt_mat = "data/datasets_matrices/Notre_Dame.mat"
