problem = "matrix-completion" 
gt_path = "datasets/data-real/Piazza_del_Popolo_gt.pt" 
shape = [1014, 1014] 
obs_path = "datasets/data-real/Piazza_del_Popolo_obs.pt" 
dataset = "Piazza_del_Popolo" 
unobs_path = "datasets/data-real/Piazza_del_Popolo_unobs.pt" 
gt_mat = "datasets/datasets_matrices/Piazza_del_Popolo.mat"
