problem = "matrix-completion" 
gt_path = "datasets/data-real/Roman_Forum_gt.pt" 
shape = [3252, 3252] 
obs_path = "datasets/data-real/Roman_Forum_obs.pt" 
dataset = "Roman_Forum" 
unobs_path = "datasets/data-real/Roman_Forum_unobs.pt" 
gt_mat = "datasets/data-real-mat/Roman_Forum.mat"
