problem = "matrix-completion" 
gt_path = "data/data-real/Tower_of_London_gt.pt" 
shape = [1416, 1416] 
obs_path = "data/data-real/Tower_of_London_obs.pt" 
dataset = "Tower_of_London" 
unobs_path = "data/data-real/Tower_of_London_unobs.pt" 
gt_mat = "data/datasets_matrices/Tower_of_London.mat"
