problem = "matrix-completion" 
gt_path = "data/data-real/Union_Square_gt.pt" 
shape = [2367, 2367] 
obs_path = "data/data-real/Union_Square_obs.pt" 
dataset = "Union_Square" 
unobs_path = "data/data-real/Union_Square_unobs.pt" 
gt_mat = "data/datasets_matrices/Union_Square.mat"
