problem = "matrix-completion" 
gt_path = "data/data-real/Yorkminster_gt.pt" 
shape = [1311, 1311] 
obs_path = "data/data-real/Yorkminster_obs.pt" 
dataset = "Yorkminster" 
unobs_path = "data/data-real/Yorkminster_unobs.pt" 
gt_mat = "data/datasets_matrices/Yorkminster.mat"
