problem = "matrix-completion" 
gt_path = "datasets/mat-synth/test_CAM_400_Out_0.4_miss_0.7_gt.pt" 
shape = [1200, 1200] 
obs_path = "datasets/mat-synth/test_CAM_400_Out_0.4_miss_0.7_obs.pt" 
dataset = "test_CAM_400_Out_0.4_miss_0.7" 
unobs_path = "datasets/mat-synth/test_CAM_400_Out_0.4_miss_0.7_unobs.pt" 
fraction_missing = 0.7 
outlier_probabilty = 0.4 
cameras = 400 
