problem = "matrix-completion" 
gt_path = "datasets/mat-cam500/test_CAM_500_Out_0.4_miss_0.5_gt.pt" 
shape = [1500, 1500] 
obs_path = "datasets/mat-cam500/test_CAM_500_Out_0.4_miss_0.5_obs.pt" 
dataset = "test_CAM_500_Out_0.4_miss_0.5" 
unobs_path = "datasets/mat-cam500/test_CAM_500_Out_0.4_miss_0.5_unobs.pt" 
fraction_missing = 0.5 
outlier_probabilty = 0.4 
cameras = 500 
