problem = "matrix-completion" 
gt_path = "datasets/mat-test/Ellis_Island_gt.pt" 
shape = [681, 681] 
obs_path = "datasets/mat-test/Ellis_Island_obs.pt" 
dataset = "Ellis_Island" 
unobs_path = "datasets/mat-test/Ellis_Island_unobs.pt" 
incomp_path = "datasets/mat-test/Ellis_Island_incomp.pt" 
