problem = "matrix-completion" 
gt_path = "datasets/mat-test/Notre_Dame_gt.pt" 
shape = [1659, 1659] 
obs_path = "datasets/mat-test/Notre_Dame_obs.pt" 
dataset = "Notre_Dame" 
unobs_path = "datasets/mat-test/Notre_Dame_unobs.pt" 
incomp_path = "datasets/mat-test/Notre_Dame_incomp.pt" 
