problem = "matrix-completion" 
gt_path = "datasets/mat-test/Trafalgar_gt.pt" 
shape = [15174, 15174] 
obs_path = "datasets/mat-test/Trafalgar_obs.pt" 
dataset = "Trafalgar" 
unobs_path = "datasets/mat-test/Trafalgar_unobs.pt" 
incomp_path = "datasets/mat-test/Trafalgar_incomp.pt" 
