problem = "matrix-completion" 
gt_path = "datasets/mat-test/Union_Square_gt.pt" 
shape = [2367, 2367] 
obs_path = "datasets/mat-test/Union_Square_obs.pt" 
dataset = "Union_Square" 
unobs_path = "datasets/mat-test/Union_Square_unobs.pt" 
incomp_path = "datasets/mat-test/Union_Square_incomp.pt" 
