problem = "matrix-completion" 
gt_path = "datasets/mat-test/Vienna_Cathedral_gt.pt" 
shape = [2508, 2508] 
obs_path = "datasets/mat-test/Vienna_Cathedral_obs.pt" 
dataset = "Vienna_Cathedral" 
unobs_path = "datasets/mat-test/Vienna_Cathedral_unobs.pt" 
incomp_path = "datasets/mat-test/Vienna_Cathedral_incomp.pt" 
